#!/bin/bash
#
# ~/bin/dwm-statusbar
#
# Status bar for dwm. Idea from:
# https://bitbucket.org/jasonwryan/eeepc/src/73dadb289dead8ef17ef29a9315ba8f1706927cb/Scripts/dwm-status

print_song_info() {
  song_info="$(ncmpcpp --now-playing '\x09{{{{%t - }%a}}|{%f}}' | head -c 75)"
  [[ ! $song_info ]] && song_info="Off"
  echo -ne "\x04\uE01D\x0F\uE00E ${song_info}"
}

print_torrent_status() {
  torrent_status="$(transmission-remote -l | awk '/\ \ Up\ &\ Down\ \ / &&\
                    ! /\ \ Unknown\ \ / {print "\\x07"$5$6}')"
  [[ ! $torrent_status ]] &&
    torrent_status="$(transmission-remote -l | awk '/\ \ Downloading\ \ / &&\
                      ! /\ \ Unknown\ \ / {print "\\x07"$5$6}')"
  [[ ! $torrent_status ]] && torrent_status="Idle"
  echo -ne "\x04\uE01C\uE01D\x0D\uE017 ${torrent_status}" | head -n 1
}

print_email_unread() {
  gmail_unread="$(find $HOME/.mutt/maildir/gmail/inbox/new -type f | wc -l)"
  mq_unread="$(find $HOME/.mutt/maildir/mq/inbox/new -type f | wc -l)"
  wongdev_unread="$(find $HOME/.mutt/maildir/wongdev/inbox/new -type f | wc -l)"
  [[ $gmail_unread -ne 0 ]] && gmail_unread="\x07${gmail_unread}\x0D"
  [[ $mq_unread -ne 0 ]] && mq_unread="\x07${mq_unread}\x0D"
  [[ $wongdev_unread -ne 0 ]] && wongdev_unread="\x07${wongdev_unread}"
  echo -ne "\x04\uE01C\uE01D\x0D\uE014 ${gmail_unread} ${mq_unread} ${wongdev_unread}"
}

print_last_msg() {
  last_msg="$(cat $HOME/.logs/irssi_pipe)"
  echo -ne "\x04\uE01C\uE01D\x0D\uE013 ${last_msg}"
}

print_mem_used() {
  mem_used="$(free -m | awk '/buffers\/cache/ {print $3}')"
  echo -ne " \x0E\uE010 \x08${mem_used}M"
}

print_volume() {
  volume="$(amixer get PCM | tail -n1 | sed -r 's/.*\[(.*)%\].*/\1/')"
  [[ $volume -ne 0 ]] && volume="\x0A${volume}"
  echo -ne "\x04\uE01C\uE01D\x10\uE015 ${volume}%"
}

print_datetime() {
  datetime="$(date "+%a %d %b \x12%H:%M")"
  echo -ne "\x04\uE01C\uE01D\x11\uE016 ${datetime}\x04\uE01C"
}

# network (from: http://dzen.geekmode.org/dwiki/doku.php?id=dzen:network-meter)
# cpu (from: https://bbs.archlinux.org/viewtopic.php?pid=661641#p661641)
rx_old=$(cat /sys/class/net/eth0/statistics/rx_bytes)
tx_old=$(cat /sys/class/net/eth0/statistics/tx_bytes)

while true; do
  # get new cpu idle and total usage
  eval $(awk '/^cpu /{print "cpu_idle_now=" $5 "; cpu_total_now=" $2+$3+$4+$5 }' /proc/stat)
  cpu_interval=$((cpu_total_now-${cpu_total_old:-0}))
  # calculate cpu usage (%)
  let cpu_used="100 * ($cpu_interval - ($cpu_idle_now-${cpu_idle_old:-0})) / $cpu_interval"

  # get new rx/tx counts
  rx_now=$(cat /sys/class/net/eth0/statistics/rx_bytes)
  tx_now=$(cat /sys/class/net/eth0/statistics/tx_bytes)
  # calculate the rate (K) and total (M)
  let rx_rate=($rx_now-$rx_old)/1024
  let tx_rate=($tx_now-$tx_old)/1024
  #  let rx_total=$rx_now/1048576
  #  let tx_total=$tx_now/1048576

  # output vars
  print_cpu_used() { printf "%-16b" "\x04\uE01C\uE01D\x0E\uE00F \x08${cpu_used}%"; }
  print_rx_rate() { printf "%-18b" "\x04\uE01C\uE01D\x0C\uE011 \x06${rx_rate}K"; }
  print_tx_rate() { printf "%-9b" "\x0B\uE012 \x05${tx_rate}K"; }

  # Pipe to status bar, not indented due to printing extra spaces/tabs
  xsetroot -name "$(print_song_info)\
$(print_torrent_status)\
$(print_email_unread)\
$(print_last_msg)\
$(print_cpu_used)$(print_mem_used)\
$(print_rx_rate)$(print_tx_rate)\
$(print_volume)\
$(print_datetime)"

  # reset old rates
  rx_old=$rx_now
  tx_old=$tx_now
  cpu_idle_old=$cpu_idle_now
  cpu_total_old=$cpu_total_now
  # loop stats every 1 second
  sleep 1
done
