#!/bin/bash
# called by xinitrc, restarts dwm without leaving X

xrdb -merge ~/.Xresources &

xset +fp /usr/share/fonts/local
xset +fp ~/.fonts
xset fp rehash
xset s off
xset dpms 3600 3600 3600
urxvtd -q -o -f
wmname LG3D &
mpd &
numlockx &
tmux &
dropboxd &
~/bin/dwm-statusbar &

while true; do
    # Log stderror to a file
    dwm 2> ~/.dwm.log
    # No error logging
    #dwm >/dev/null 2>&1
done
