#!/bin/bash
if [[ -z $1 ]]; then
  echo "Error: No channel specified."
  exit 1
fi

playlist="$HOME/videos/iptv_playlist"

if [[ -f "$playlist" ]]; then
  search_results="$(grep -i "$1" $playlist)"
  num_results=$(echo "$search_results" | wc -l)

  if [[ -z "$search_results" ]]; then
    echo "Channel not found"
    exit 1
  elif [[ $num_results > 1 ]]; then
    echo "$search_results"
    echo -e "\nMultitple results found. Refine search."
    exit 1
  else 
    /usr/bin/mplayer -really-quiet -cache 2048 "$search_results"
  fi
else
  echo "Playlist not found"
  exit 1
fi
